### PR TITLE
MINOR proxyfix

### PR DESCRIPTION
**Pull request by spekulatius**
Hello @fb3rasp,

I run into an issue where the API of current version of the mapserver takes the parameters differently. "body=" is no longer supported. I'm not sure when this change happened. Its up to you if you want to merge this (and create a new release for this).

Cheers,
Peter

### CODE REVIEW

**Comment by dhensby** [comment]
this needs rebasing before it can be merged

**Comment by spekulatius** [comment]
Done @zarocknz @zarocknz

**Comment by dhensby** [comment]
oh great, I don't have merge rights. @tractorcow !!!

**Comment by tractorcow** [comment]
You do now!

**Comment by dhensby** [comment]
thanks!

**Pull request merged**
